//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon_Base_Stats_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pokemon_Base_Stats_Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Stench
        ///2,Drizzle
        ///3,Speed Boost
        ///4,Battle Armor
        ///5,Sturdy
        ///6,Damp
        ///7,Limber
        ///8,Sand Veil
        ///9,Static
        ///10,Volt Absorb
        ///11,Water Absorb
        ///12,Oblivious
        ///13,Cloud Nine
        ///14,Compoundeyes
        ///15,Insomnia
        ///16,Color Change
        ///17,Immunity
        ///18,Flash Fire
        ///19,Shield Dust
        ///20,Own Tempo
        ///21,Suction Cups
        ///22,Intimidate
        ///23,Shadow Tag
        ///24,Rough Skin
        ///25,Wonder Guard
        ///26,Levitate
        ///27,Effect Spore
        ///28,Synchronize
        ///29,Clear Body
        ///30,Natural Cure
        ///31,Lightningrod
        ///32,Serene Grace
        ///33,Swift Swim
        ///34,Chlorophyll
        ///35,Illuminate
        ///36,Tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string abilities {
            get {
                return ResourceManager.GetString("abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Ball 
        ///Ultra Ball 
        ///Great Ball 
        ///Poké Ball 
        ///Safari Ball 
        ///Net Ball 
        ///Dive Ball 
        ///Nest Ball 
        ///Repeat Ball 
        ///Timer Ball 
        ///Luxury Ball 
        ///Premier Ball 
        ///Dusk Ball 
        ///Heal Ball 
        ///Quick Ball 
        ///Cherish Ball 
        ///Potion 
        ///Antidote 
        ///Burn Heal 
        ///Ice Heal 
        ///Awakening 
        ///Parlyz Heal 
        ///Full Restore 
        ///Max Potion 
        ///Hyper Potion 
        ///Super Potion 
        ///Full Heal 
        ///Revive 
        ///Max Revive 
        ///Fresh Water 
        ///Soda Pop 
        ///Lemonade 
        ///Moomoo Milk 
        ///EnergyPowder 
        ///Energy Root 
        ///Heal Powder 
        ///Revival Herb 
        ///Ether 
        ///Max Ether 
        ///Elixir 
        ///Max E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound
        ///Karate Chop
        ///DoubleSlap
        ///Comet Punch
        ///Mega Punch
        ///Pay Day
        ///Fire Punch
        ///Ice Punch
        ///ThunderPunch
        ///Scratch
        ///ViceGrip
        ///Guillotine
        ///Razor Wind
        ///Swords Dance
        ///Cut
        ///Gust
        ///Wing Attack
        ///Whirlwind
        ///Fly
        ///Bind
        ///Slam
        ///Vine Whip
        ///Stomp
        ///Double Kick
        ///Mega Kick
        ///Jump Kick
        ///Rolling Kick
        ///Sand-Attack
        ///Headbutt
        ///Horn Attack
        ///Fury Attack
        ///Horn Drill
        ///Tackle
        ///Body Slam
        ///Wrap
        ///Take Down
        ///Thrash
        ///Double-Edge
        ///Tail Whip
        ///Poison Sting
        ///Twineedle
        ///Pin Missile
        ///Leer
        ///Bite
        ///Growl
        ///Roar
        ///Sing
        ///Supersonic
        ///SonicBoom
        ///Disable
        ///Acid
        ///Ember
        ///Flamethrower
        ///Mist
        ///Water Gun
        ///Hydro Pump
        ///Sur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moves {
            get {
                return ResourceManager.GetString("moves", resourceCulture);
            }
        }
    }
}
